// getifaddrs_bridge_server.c  --  This file is part of tiny_computer.               
                                                                        
// Copyright (C) 2023 Caten Hu                                          
                                                                        
// Tiny Computer is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published    
// by the Free Software Foundation, either version 3 of the License,    
// or any later version.                               
                                                                         
// Tiny Computer is distributed in the hope that it will be useful,          
// but WITHOUT ANY WARRANTY; without even the implied warranty          
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.              
// See the GNU General Public License for more details.                 
                                                                     
// You should have received a copy of the GNU General Public License    
// along with this program.  If not, see http://www.gnu.org/licenses/.
//
// 本文件经由 AI 修改（2026-09-20），修复见下方 TINY-OPT 注释。

/* this file is mainly generated by Bing */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <ifaddrs.h>
#include <sys/ioctl.h>
#include <net/if.h>
#include <sys/un.h>

#ifdef __linux__
#include <sys/prctl.h>
#endif

// TINY-OPT[1]: 协议改动，与客户端保持一致。每帧 = magic(4B) + 大端长度(4B) + 载荷。
// 原协议没有任何帧标记与长度字段，靠逐字段偏移对齐，短写/截断都会静默错位。
#define TINY_FRAME_MAGIC 0x54494631u /* 'TIF1' */
#define TINY_FRAME_HDR 8

static uint32_t tiny_rd32be(const unsigned char *p) {
    return ((uint32_t)p[0] << 24) | ((uint32_t)p[1] << 16) | ((uint32_t)p[2] << 8) | (uint32_t)p[3];
}

static void tiny_wr32be(unsigned char *p, uint32_t v) {
    p[0] = (unsigned char)(v >> 24);
    p[1] = (unsigned char)(v >> 16);
    p[2] = (unsigned char)(v >> 8);
    p[3] = (unsigned char)v;
}

// TINY-OPT[2]: 原实现 read()/write() 各调用一次即当成功；socket 上是允许短读短写的。
static ssize_t tiny_read_full(int fd, void *buf, size_t len) {
    unsigned char *p = (unsigned char *)buf;
    size_t got = 0;
    while (got < len) {
        ssize_t n = read(fd, p + got, len - got);
        if (n == 0) { errno = ECONNRESET; return -1; }
        if (n < 0) {
            if (errno == EINTR) continue;
            return -1;
        }
        got += (size_t)n;
    }
    return (ssize_t)got;
}

static ssize_t tiny_write_full(int fd, const void *buf, size_t len) {
    const unsigned char *p = (const unsigned char *)buf;
    size_t sent = 0;
    while (sent < len) {
        ssize_t n = write(fd, p + sent, len - sent);
        if (n <= 0) {
            if (n < 0 && errno == EINTR) continue;
            return -1;
        }
        sent += (size_t)n;
    }
    return (ssize_t)sent;
}

// TINY-OPT[3]: 原实现把每个地址都按 sizeof(struct sockaddr)=16 字节写入，
// AF_INET6(28B)、AF_PACKET(20B) 会被截断，容器内 inet_ntop/getnameinfo 拿到的是
// 垃圾地址。这里按族给出真实长度，原样搬运。
static int sa_len(const struct sockaddr *sa) {
    if (sa == NULL) return 0;
    switch (sa->sa_family) {
        case AF_INET:   return (int)sizeof(struct sockaddr_in);
        case AF_INET6:  return (int)sizeof(struct sockaddr_in6);
        case AF_PACKET: return (int)sizeof(struct sockaddr_ll);
        default:        return (int)sizeof(struct sockaddr);
    }
}

// 单个地址字段：kind(1B) [+ family(1B) + len(2B, LE) + 原始字节]
static int put_sockaddr(char *buf, int size, int len, const struct sockaddr *sa) {
    if (sa == NULL) {
        if (len + 1 > size) return -1;
        buf[len] = '\0';
        return len + 1;
    }
    int alen = sa_len(sa);
    if (alen <= 0 || len + 4 + alen > size) return -1;
    buf[len] = '\1';
    buf[len + 1] = (char)(sa->sa_family & 0xFF);
    buf[len + 2] = (char)(alen & 0xFF);
    buf[len + 3] = (char)((alen >> 8) & 0xFF);
    memcpy(buf + len + 4, sa, (size_t)alen);
    return len + 4 + alen;
}

// 定义一个序列化函数，将ifaddrs结构体转换为字节数组。
// 返回 >=0 表示写入长度；-1 表示缓冲区不足或字段异常（调用方必须当成失败，不能发半截数据）。
int serialize_ifaddrs(struct ifaddrs *ifa, char *buf, int size) {
    int len = 0; // 记录已经写入的字节数
    while (ifa != NULL) {
        // 写入接口名称
        size_t namelen = strlen(ifa->ifa_name) + 1; // 包括结束符
        if (len + (int)namelen + (int)sizeof(unsigned int) > size) return -1;
        memcpy(buf + len, ifa->ifa_name, namelen);
        len += (int)namelen;
        // 写入接口标志
        memcpy(buf + len, &ifa->ifa_flags, sizeof(unsigned int));
        len += (int)sizeof(unsigned int);
        // TINY-OPT[4]: 原实现在 IFF_BROADCAST 与 IFF_POINTOPOINT 都不成立时写两个空字节，
        // 客户端也只跳 2 字节 —— 双方“一致地错”，字段会整体错位。现在固定写 4 个字段：
        // addr / netmask / (dstaddr|broadaddr) / data，每个字段自带 kind。
        const struct sockaddr *third =
            (ifa->ifa_flags & IFF_POINTOPOINT) ? ifa->ifa_dstaddr : ifa->ifa_broadaddr;
        const struct sockaddr *fields[4];
        fields[0] = ifa->ifa_addr;
        fields[1] = ifa->ifa_netmask;
        fields[2] = third;
        fields[3] = NULL; // ifa_data 不透传（原实现也只是写一个空字节）
        for (int i = 0; i < 4; i++) {
            int nlen = put_sockaddr(buf, size, len, fields[i]);
            if (nlen < 0) return -1;
            len = nlen;
        }
        // 跳到下一个接口
        ifa = ifa->ifa_next;
    }
    return len; // 返回写入的总字节数
}

// 定义一个接收信号的函数，从客户端接收一个请求帧
int receive_signal(int sockfd) {
    unsigned char hdr[TINY_FRAME_HDR];
    if (tiny_read_full(sockfd, hdr, sizeof(hdr)) < 0) return -1;
    if (tiny_rd32be(hdr) != TINY_FRAME_MAGIC) {
        fprintf(stderr, "getifaddrs_bridge: bad frame magic from client\n");
        return -1;
    }
    uint32_t body = tiny_rd32be(hdr + 4);
    if (body != 1) {
        fprintf(stderr, "getifaddrs_bridge: bad request length %u\n", body);
        return -1;
    }
    char sig = 0;
    if (tiny_read_full(sockfd, &sig, 1) < 0) return -1;
    if (sig == 'S') return 0; // 客户端需要数据
    fprintf(stderr, "getifaddrs_bridge: invalid signal: %c\n", sig);
    return -1;
}

// 定义一个发送数据的函数，向客户端发送数据并序列化
int send_data(int sockfd) {
    struct ifaddrs *ifap = NULL; // 定义ifaddrs结构体指针
    char *buf = NULL;
    int ret = -1;
    int len;
    int cap = 16 * 1024; // TINY-OPT[5]: 动态缓冲。原实现是固定 1024 字节栈缓冲，
                         // 接口一多就静默截断（客户端还会把截断结果当成功）。

    if (getifaddrs(&ifap) < 0) {
        perror("getifaddrs");
        return -1; // 返回错误
    }
    // 先试小缓冲，不够再翻倍重试
    for (;;) {
        buf = (char *)malloc((size_t)cap);
        if (buf == NULL) goto out;
        len = serialize_ifaddrs(ifap, buf, cap);
        if (len >= 0) break;
        free(buf);
        buf = NULL;
        if (cap >= 4 * 1024 * 1024) {
            fprintf(stderr, "getifaddrs_bridge: interface table too large\n");
            goto out;
        }
        cap *= 2;
    }

    unsigned char hdr[TINY_FRAME_HDR];
    tiny_wr32be(hdr, TINY_FRAME_MAGIC);
    tiny_wr32be(hdr + 4, (uint32_t)len);
    if (tiny_write_full(sockfd, hdr, sizeof(hdr)) < 0) {
        perror("write");
        goto out;
    }
    if (tiny_write_full(sockfd, buf, (size_t)len) < 0) {
        perror("write");
        goto out;
    }
    ret = 0; // 返回成功

out:
    // TINY-OPT[6]: 原实现在 write 失败的路径上 return -1 而没有 freeifaddrs(ifap)，
    // 每次失败泄漏整份接口表。
    if (buf != NULL) free(buf);
    if (ifap != NULL) freeifaddrs(ifap);
    return ret;
}

// TINY-OPT[7]: 单实例。原实现每次 App 启动容器都新起一个 server，旧进程会变成
// 孤儿永久阻塞在 accept（socket 文件被新进程 unlink 后旧进程再也收不到连接）。
static int acquire_single_instance(const char *lock_path) {
    int fd = open(lock_path, O_CREAT | O_RDWR, 0600);
    if (fd < 0) return -1;
    if (flock(fd, LOCK_EX | LOCK_NB) != 0) {
        close(fd);
        return -1; // 已有实例在跑
    }
    return fd; // 保持 fd 打开以持有锁
}

// 主函数
int main(int argc, char *argv[]) {
    if (argc != 2) {
        printf("usage: %s <socket_path>\n", argv[0]);
        return 0;
    }

    // TINY-OPT[8]: 原实现没有屏蔽 SIGPIPE —— 客户端提前关闭时 write 会直接杀掉本进程，
    // 之后容器内所有 LD_PRELOAD 了客户端库的程序都会因为桥消失而受影响。
    signal(SIGPIPE, SIG_IGN);

#ifdef __linux__
    // 父进程（App）退出后自动收尸，避免残留进程
    prctl(PR_SET_PDEATHSIG, SIGTERM);
#endif

    const char *lock_path = getenv("TINY_BRIDGE_LOCK");
    if (lock_path == NULL || lock_path[0] == '\0') {
        lock_path = "/tmp/.getifaddrs-bridge.lock";
    }
    int lockfd = acquire_single_instance(lock_path);
    if (lockfd < 0) {
        fprintf(stderr, "getifaddrs_bridge: another instance is already running, exit\n");
        return 0;
    }

    // 创建一个套接字
    int sockfd = socket(PF_UNIX, SOCK_STREAM, 0);
    if (sockfd < 0) {
        perror("socket");
        return 1;
    }
    // 定义服务器地址结构体
    struct sockaddr_un un;
    memset(&un, 0, sizeof(un));
    un.sun_family = AF_UNIX;
    snprintf(un.sun_path, sizeof(un.sun_path), "%s", argv[1]);
    // TINY-OPT[12]: 原来无条件 unlink 路径上的 socket 文件。单实例锁在上一步已经保证
    // 不会有别的 server 在跑，这里对普通文件直接报错，避免误删别的东西。
    struct stat st;
    if (lstat(un.sun_path, &st) == 0 && !S_ISSOCK(st.st_mode)) {
        fprintf(stderr, "getifaddrs_bridge: %s exists and is not a socket\n", un.sun_path);
        return 1;
    }
    unlink(un.sun_path);
    // 绑定套接字到服务器地址
    if (bind(sockfd, (struct sockaddr *)&un, sizeof(un)) < 0) {
        perror("bind");
        return 1;
    }
    // TINY-OPT[9]: 原实现 socket 权限由 umask 决定（默认 0755，同机其它 uid 也能连）。
    // 这里收紧到 0600，只有容器所属 uid（App 自己）可访问。
    chmod(un.sun_path, 0600);
    // 监听套接字
    if (listen(sockfd, 5) < 0) {
        perror("listen");
        return 1;
    }
    // 循环接受客户端连接
    while (1) {
        int connfd = accept(sockfd, NULL, NULL);
        if (connfd < 0) {
            if (errno == EINTR) continue; // TINY-OPT[10]: 被信号打断不算错误
            perror("accept");
            continue; // 如果接受失败，继续循环
        }
        // TINY-OPT[11]: 原实现单线程、read 无超时，一个连上却不发数据的客户端就能
        // 阻塞掉所有其它客户端。这里给每条连接设 2 秒收发超时。
        struct timeval tv;
        tv.tv_sec = 2;
        tv.tv_usec = 0;
        setsockopt(connfd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
        setsockopt(connfd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));
        // 循环接收和发送数据
        while (1) {
            // 接收信号
            if (receive_signal(connfd) < 0) {
                close(connfd); // 如果接收失败，关闭连接套接字
                break; // 跳出循环
            }
            // 发送数据
            if (send_data(connfd) < 0) {
                close(connfd); // 如果发送失败，关闭连接套接字
                break; // 跳出循环
            }
        }
    }
    // 关闭监听套接字
    close(sockfd);
    close(lockfd);
    return 0;
}
