// getifaddrs_bridge_client_lib.c  --  This file is part of tiny_computer.               
                                                                        
// Copyright (C) 2023 Caten Hu                                          
                                                                        
// Tiny Computer is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published    
// by the Free Software Foundation, either version 3 of the License,    
// or any later version.                               
                                                                         
// Tiny Computer is distributed in the hope that it will be useful,          
// but WITHOUT ANY WARRANTY; without even the implied warranty          
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.              
// See the GNU General Public License for more details.                 
                                                                     
// You should have received a copy of the GNU General Public License    
// along with this program.  If not, see http://www.gnu.org/licenses/.
//
// 本文件经由 AI 修改（2026-09-20），修复见下方 TINY-OPT 注释。

/* this file is mainly generated by Bing */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <dlfcn.h>
#include <signal.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <ifaddrs.h>
#include <sys/ioctl.h>
#include <net/if.h>
#include <sys/un.h>

#define BUFSIZE 1024 // 定义缓冲区大小

// TINY-OPT[1]: 协议改动。原协议没有任何帧标记与长度字段，客户端 / 服务端只靠
// “逐字段偏移 + buf[len] != '\0' 探测” 对齐，任何短读、短写、截断或版本错配都会
// 让双方静默错位。这里在每帧前面加 4 字节大端长度，并配 read_full / write_full
// 循环，保证“要么完整收到一帧，要么明确失败”。
#define TINY_FRAME_MAGIC 0x54494631u /* 'TIF1' */
#define TINY_FRAME_HDR 8

static uint32_t tiny_rd32be(const unsigned char *p) {
    return ((uint32_t)p[0] << 24) | ((uint32_t)p[1] << 16) | ((uint32_t)p[2] << 8) | (uint32_t)p[3];
}

static void tiny_wr32be(unsigned char *p, uint32_t v) {
    p[0] = (unsigned char)(v >> 24);
    p[1] = (unsigned char)(v >> 16);
    p[2] = (unsigned char)(v >> 8);
    p[3] = (unsigned char)v;
}

// TINY-OPT[2]: 原实现用 read()/write() 各调用一次就当成功；socket 上是允许短读短写的。
static ssize_t tiny_read_full(int fd, void *buf, size_t len, int timeoutSec) {
    unsigned char *p = (unsigned char *)buf;
    size_t got = 0;
    if (timeoutSec > 0) {
        struct timeval tv;
        tv.tv_sec = timeoutSec;
        tv.tv_usec = 0;
        setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
    }
    while (got < len) {
        ssize_t n = read(fd, p + got, len - got);
        if (n == 0) { errno = ECONNRESET; return -1; }      // 对端提前关闭
        if (n < 0) {
            if (errno == EINTR) continue;                    // 被信号打断，重试
            return -1;
        }
        got += (size_t)n;
    }
    return (ssize_t)got;
}

static ssize_t tiny_write_full(int fd, const void *buf, size_t len) {
    const unsigned char *p = (const unsigned char *)buf;
    size_t sent = 0;
    while (sent < len) {
        ssize_t n = write(fd, p + sent, len - sent);
        if (n <= 0) {
            if (n < 0 && errno == EINTR) continue;
            return -1;
        }
        sent += (size_t)n;
    }
    return (ssize_t)sent;
}

// 定义一个反序列化函数，将字节数组转换为ifaddrs结构体
int TINY_deserialize_ifaddrs(const char *buf, int size, struct ifaddrs **ifap) {
    int len = 0; // 记录已经读取的字节数
    struct ifaddrs *head = NULL; // 链表头指针
    struct ifaddrs *tail = NULL; // 链表尾指针
    while (len < size) {
        // TINY-OPT[3]: 原实现用 strlen(buf + len) 取接口名，但wire上不保证有 NUL，
        // 数据损坏时会一路读到缓冲区外。这里改成有界查找。
        const char *name = buf + len;
        size_t maxname = (size_t)(size - len);
        size_t namelen0 = strnlen(name, maxname);
        if (namelen0 == 0 || namelen0 >= maxname) break; // 空名字 / 没有结束符 → 数据损坏
        int namelen = (int)namelen0 + 1; // 包括结束符
        if (len + namelen > size) break; // 缓冲区不足
        // 为当前接口分配内存
        struct ifaddrs *ifa = (struct ifaddrs *)calloc(1, sizeof(struct ifaddrs));
        if (ifa == NULL) {
            freeifaddrs(head);
            return -1; // 返回错误
        }
        ifa->ifa_name = (char *)malloc((size_t)namelen); // 为名称分配内存
        if (ifa->ifa_name == NULL) {
            free(ifa);
            freeifaddrs(head);
            return -1; // 返回错误
        }
        memcpy(ifa->ifa_name, buf + len, (size_t)namelen); // 复制名称
        len += namelen;
        // 读取接口标志
        if (len + (int)sizeof(unsigned int) > size) break; // 缓冲区不足
        memcpy(&ifa->ifa_flags, buf + len, sizeof(unsigned int)); // 复制标志
        len += (int)sizeof(unsigned int);

        // TINY-OPT[4]: 地址字段。原实现写死 sizeof(struct sockaddr)=16 字节并按族截断，
        // AF_INET6(28B)/AF_PACKET(20B) 会被砍掉后半段。新协议带 family+len，各族原样搬运。
        struct sockaddr **field[4];
        field[0] = &ifa->ifa_addr;
        field[1] = &ifa->ifa_netmask;
        field[2] = (ifa->ifa_flags & IFF_POINTOPOINT) ? &ifa->ifa_dstaddr : &ifa->ifa_broadaddr;
        field[3] = NULL; // ifa_data 目前不透传，保持 NULL
        for (int i = 0; i < 4; i++) {
            // addr_kind: 0 = 该字段为 NULL，1 = 后面跟完整 sockaddr
            if (len + 1 > size) { goto corrupted; }
            unsigned char kind = (unsigned char)buf[len];
            len += 1;
            if (kind == 0) {
                if (i == 2) {
                    // 广播地址与点对点地址在 ifaddrs 里是同一个 union，清干净
                    ifa->ifa_broadaddr = NULL;
                    ifa->ifa_dstaddr = NULL;
                }
                continue;
            }
            if (len + 3 > size) { goto corrupted; }
            unsigned int family = (unsigned char)buf[len];
            unsigned int alen = (unsigned int)(unsigned char)buf[len + 1] |
                                ((unsigned int)(unsigned char)buf[len + 2] << 8);
            len += 3;
            if (alen < 2 || alen > 128) { goto corrupted; }       // 长度上限，防越界
            if (len + (int)alen > size) { goto corrupted; }
            struct sockaddr *addr = (struct sockaddr *)calloc(1, alen);
            if (addr == NULL) {
                freeifaddrs(head);
                free(ifa->ifa_name);
                free(ifa);
                return -1;
            }
            memcpy(addr, buf + len, alen);
            addr->sa_family = (sa_family_t)family;
            if (field[i] != NULL) *field[i] = addr;
            len += (int)alen;
        }
        ifa->ifa_data = NULL;
        // 将当前接口插入链表
        ifa->ifa_next = NULL;
        if (head == NULL) {
            head = ifa; // 如果是第一个接口，设置头指针
        } else {
            tail->ifa_next = ifa; // 如果不是第一个接口，设置尾指针的下一个指针
        }
        tail = ifa; // 更新尾指针
        continue;

corrupted:
        // TINY-OPT[5]: 原实现遇到数据不完整只是 break，然后把残缺链表当成成功结果返回。
        // 这里明确失败，让调用方回退到真实 getifaddrs。
        freeifaddrs(head);
        return -1;
    }
    *ifap = head; // 返回链表头指针
    return len; // 返回读取的总字节数
}

// 定义一个发送信号的函数，向服务器发送一个信号
int TINY_send_signal(int sockfd) {
    unsigned char hdr[TINY_FRAME_HDR]; // TINY-OPT[1]: 带长度头的请求帧
    tiny_wr32be(hdr, TINY_FRAME_MAGIC);
    tiny_wr32be(hdr + 4, 1); // 请求体 1 字节：'S'
    if (tiny_write_full(sockfd, hdr, sizeof(hdr)) < 0) return -1;
    if (tiny_write_full(sockfd, "S", 1) < 0) return -1;
    return 0; // 返回成功
}

// 定义一个接收数据的函数，从服务器接收数据并反序列化
int TINY_receive_data(int sockfd, struct ifaddrs **ifap) {
    unsigned char hdr[TINY_FRAME_HDR];
    if (tiny_read_full(sockfd, hdr, sizeof(hdr), 10) < 0) return -1;
    if (tiny_rd32be(hdr) != TINY_FRAME_MAGIC) { errno = EBADMSG; return -1; }
    uint32_t body = tiny_rd32be(hdr + 4);
    // TINY-OPT[6]: 原实现是 char buf[1024] + 单次 read，且如果换个更大的 rootfs
    // 造成接口数量增加，服务端也会截断。这里按帧长动态分配，并设置上限避免被恶意的
    // 长度字段诱导分配巨量内存。
    if (body == 0) { *ifap = NULL; return 0; }
    if (body > 16 * 1024 * 1024u) { errno = EMSGSIZE; return -1; }
    char *buf = (char *)malloc(body);
    if (buf == NULL) return -1;
    if (tiny_read_full(sockfd, buf, body, 10) < 0) {
        free(buf);
        return -1;
    }
    int len = TINY_deserialize_ifaddrs(buf, (int)body, ifap); // 反序列化数据
    free(buf);
    if (len < 0) {
        return -1; // 返回错误
    }
    return 0; // 返回成功
}

// TINY-OPT[7]: 主函数。原实现在 socket/connect/收发失败时直接 exit(1)，而本库是用
// LD_PRELOAD 覆盖 libc 的 getifaddrs 的，于是“桥没跑起来”会变成“容器内所有调用
// getifaddrs 的程序被杀死”。现在失败时改为回退到真实实现（dlsym(RTLD_NEXT)），
// 桥不可用只是退化为原生行为，绝不终止进程。
static int (*tiny_real_getifaddrs)(struct ifaddrs **) = NULL;

int getifaddrs(struct ifaddrs **ifap) {
    int saved_errno;
    int sockfd = -1;
    int ok = 0;
    struct sockaddr_un un;

    // TINY-OPT[8]: 一次 getifaddrs 全流程只写一次 socket，被 SIGPIPE 杀掉的高风险点
    // 直接屏蔽（本库不还原进程原有的 handler，保持简单）。
    signal(SIGPIPE, SIG_IGN);

    if (ifap == NULL) { errno = EINVAL; return -1; }

    sockfd = socket(PF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
    if (sockfd < 0) goto fallback;

    memset(&un, 0, sizeof(un));
    un.sun_family = AF_UNIX;
    snprintf(un.sun_path, sizeof(un.sun_path), "%s", "/tmp/.getifaddrs-bridge");

    // TINY-OPT[9]: 原实现用 connect() 的默认超时（阻塞到内核放弃）。bridge 若挂死，
    // 容器里每个调用 getifaddrs 的进程都会一起挂起。这里给 3 秒上限。
    struct timeval tv;
    tv.tv_sec = 3;
    tv.tv_usec = 0;
    setsockopt(sockfd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));

    if (connect(sockfd, (struct sockaddr *)&un, sizeof(un)) < 0) goto fallback;
    if (TINY_send_signal(sockfd) < 0) goto fallback;
    if (TINY_receive_data(sockfd, ifap) < 0) goto fallback;

    ok = 1;

fallback:
    saved_errno = errno;
    if (sockfd >= 0) close(sockfd);
    if (ok) return 0;

    if (tiny_real_getifaddrs == NULL) {
        // RTLD_NEXT：取本库之后的下一个 getifaddrs，也就是 libc 的实现。
        // 经 void* 中转赋值，避免部分编译器对函数指针/数据指针转换的告警。
        void *sym = dlsym(RTLD_NEXT, "getifaddrs");
        memcpy(&tiny_real_getifaddrs, &sym, sizeof(sym));
    }
    if (tiny_real_getifaddrs != NULL) {
        return tiny_real_getifaddrs(ifap);
    }
    errno = saved_errno;
    return -1;
}
